[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
phases = ["setup", "install", "build"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npm run prisma:migrate && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
