[phases.setup]
nixPkgs = ['nodejs', 'nginx']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'echo "VITE_API_URL=${VITE_API_URL}" > .env',
  'npm run build'
]

[start]
cmd = '/start-nginx.sh'
